/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CardRouteImport } from './routes/card'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as QuoteIndexRouteImport } from './routes/quote.index'
import { Route as QuoteTokenRouteImport } from './routes/quote.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminRequestsIndexRouteImport } from './routes/_authenticated/admin.requests.index'
import { Route as AuthenticatedAdminRequestsIdRouteImport } from './routes/_authenticated/admin.requests.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIndexRoute = QuoteIndexRouteImport.update({
  id: '/quote/',
  path: '/quote/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteTokenRoute = QuoteTokenRouteImport.update({
  id: '/quote/$token',
  path: '/quote/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRequestsIndexRoute =
  AuthenticatedAdminRequestsIndexRouteImport.update({
    id: '/admin/requests/',
    path: '/admin/requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRequestsIdRoute =
  AuthenticatedAdminRequestsIdRouteImport.update({
    id: '/admin/requests/$id',
    path: '/admin/requests/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/admin/login': typeof AdminLoginRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/quote/': typeof QuoteIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
  '/admin/requests/': typeof AuthenticatedAdminRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/admin/login': typeof AdminLoginRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/quote': typeof QuoteIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/admin/login': typeof AdminLoginRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/quote/': typeof QuoteIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
  '/_authenticated/admin/requests/': typeof AuthenticatedAdminRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/card'
    | '/admin/login'
    | '/quote/$token'
    | '/quote/'
    | '/admin/'
    | '/admin/requests/$id'
    | '/admin/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/card'
    | '/admin/login'
    | '/quote/$token'
    | '/quote'
    | '/admin'
    | '/admin/requests/$id'
    | '/admin/requests'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/card'
    | '/admin/login'
    | '/quote/$token'
    | '/quote/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/requests/$id'
    | '/_authenticated/admin/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CardRoute: typeof CardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  QuoteTokenRoute: typeof QuoteTokenRoute
  QuoteIndexRoute: typeof QuoteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/': {
      id: '/quote/'
      path: '/quote'
      fullPath: '/quote/'
      preLoaderRoute: typeof QuoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$token': {
      id: '/quote/$token'
      path: '/quote/$token'
      fullPath: '/quote/$token'
      preLoaderRoute: typeof QuoteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/requests/': {
      id: '/_authenticated/admin/requests/'
      path: '/admin/requests'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AuthenticatedAdminRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/requests/$id': {
      id: '/_authenticated/admin/requests/$id'
      path: '/admin/requests/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AuthenticatedAdminRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminRequestsIdRoute: typeof AuthenticatedAdminRequestsIdRoute
  AuthenticatedAdminRequestsIndexRoute: typeof AuthenticatedAdminRequestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminRequestsIdRoute: AuthenticatedAdminRequestsIdRoute,
  AuthenticatedAdminRequestsIndexRoute: AuthenticatedAdminRequestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CardRoute: CardRoute,
  AdminLoginRoute: AdminLoginRoute,
  QuoteTokenRoute: QuoteTokenRoute,
  QuoteIndexRoute: QuoteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
