/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DriverRouteRouteImport } from './routes/_driver/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CardRouteImport } from './routes/card'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as QuoteIndexRouteImport } from './routes/quote.index'
import { Route as QuoteTokenRouteImport } from './routes/quote.$token'
import { Route as ReplyTokenRouteImport } from './routes/reply.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as DriverGarageIndexRouteImport } from './routes/_driver/garage.index'
import { Route as DriverGarageAddRouteImport } from './routes/_driver/garage.add'
import { Route as DriverGarageAskRouteImport } from './routes/_driver/garage.ask'
import { Route as DriverGarageMyCarRouteImport } from './routes/_driver/garage.my-car'
import { Route as DriverGarageNotificationsRouteImport } from './routes/_driver/garage.notifications'
import { Route as DriverGarageProfileRouteImport } from './routes/_driver/garage.profile'
import { Route as DriverGarageServiceRouteImport } from './routes/_driver/garage.service'
import { Route as DriverProviderIndexRouteImport } from './routes/_driver/provider.index'
import { Route as DriverProviderOnboardingRouteImport } from './routes/_driver/provider.onboarding'
import { Route as DriverProviderProfileRouteImport } from './routes/_driver/provider.profile'
import { Route as DriverProviderRequestsRouteImport } from './routes/_driver/provider.requests'
import { Route as DriverProviderSettingsRouteImport } from './routes/_driver/provider.settings'
import { Route as AuthenticatedAdminProvidersIndexRouteImport } from './routes/_authenticated/admin.providers.index'
import { Route as AuthenticatedAdminRequestsIndexRouteImport } from './routes/_authenticated/admin.requests.index'
import { Route as AuthenticatedAdminRequestsIdRouteImport } from './routes/_authenticated/admin.requests.$id'
import { Route as DriverGarageBuildBuildIdRouteImport } from './routes/_driver/garage.build.$buildId'
import { Route as DriverGarageRequestIdRouteImport } from './routes/_driver/garage.request.$id'
import { Route as DriverGarageVehicleIdRouteImport } from './routes/_driver/garage.vehicle.$id'
import { Route as DriverProviderProjectIdRouteImport } from './routes/_driver/provider.project.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRouteRoute = DriverRouteRouteImport.update({
  id: '/_driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIndexRoute = QuoteIndexRouteImport.update({
  id: '/quote/',
  path: '/quote/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteTokenRoute = QuoteTokenRouteImport.update({
  id: '/quote/$token',
  path: '/quote/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplyTokenRoute = ReplyTokenRouteImport.update({
  id: '/reply/$token',
  path: '/reply/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DriverGarageIndexRoute = DriverGarageIndexRouteImport.update({
  id: '/garage/',
  path: '/garage/',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverGarageAddRoute = DriverGarageAddRouteImport.update({
  id: '/garage/add',
  path: '/garage/add',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverGarageAskRoute = DriverGarageAskRouteImport.update({
  id: '/garage/ask',
  path: '/garage/ask',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverGarageMyCarRoute = DriverGarageMyCarRouteImport.update({
  id: '/garage/my-car',
  path: '/garage/my-car',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverGarageNotificationsRoute =
  DriverGarageNotificationsRouteImport.update({
    id: '/garage/notifications',
    path: '/garage/notifications',
    getParentRoute: () => DriverRouteRoute,
  } as any)
const DriverGarageProfileRoute = DriverGarageProfileRouteImport.update({
  id: '/garage/profile',
  path: '/garage/profile',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverGarageServiceRoute = DriverGarageServiceRouteImport.update({
  id: '/garage/service',
  path: '/garage/service',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverProviderIndexRoute = DriverProviderIndexRouteImport.update({
  id: '/provider/',
  path: '/provider/',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverProviderOnboardingRoute =
  DriverProviderOnboardingRouteImport.update({
    id: '/provider/onboarding',
    path: '/provider/onboarding',
    getParentRoute: () => DriverRouteRoute,
  } as any)
const DriverProviderProfileRoute = DriverProviderProfileRouteImport.update({
  id: '/provider/profile',
  path: '/provider/profile',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverProviderRequestsRoute = DriverProviderRequestsRouteImport.update({
  id: '/provider/requests',
  path: '/provider/requests',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverProviderSettingsRoute = DriverProviderSettingsRouteImport.update({
  id: '/provider/settings',
  path: '/provider/settings',
  getParentRoute: () => DriverRouteRoute,
} as any)
const AuthenticatedAdminProvidersIndexRoute =
  AuthenticatedAdminProvidersIndexRouteImport.update({
    id: '/admin/providers/',
    path: '/admin/providers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRequestsIndexRoute =
  AuthenticatedAdminRequestsIndexRouteImport.update({
    id: '/admin/requests/',
    path: '/admin/requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRequestsIdRoute =
  AuthenticatedAdminRequestsIdRouteImport.update({
    id: '/admin/requests/$id',
    path: '/admin/requests/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DriverGarageBuildBuildIdRoute =
  DriverGarageBuildBuildIdRouteImport.update({
    id: '/garage/build/$buildId',
    path: '/garage/build/$buildId',
    getParentRoute: () => DriverRouteRoute,
  } as any)
const DriverGarageRequestIdRoute = DriverGarageRequestIdRouteImport.update({
  id: '/garage/request/$id',
  path: '/garage/request/$id',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverGarageVehicleIdRoute = DriverGarageVehicleIdRouteImport.update({
  id: '/garage/vehicle/$id',
  path: '/garage/vehicle/$id',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverProviderProjectIdRoute = DriverProviderProjectIdRouteImport.update({
  id: '/provider/project/$id',
  path: '/provider/project/$id',
  getParentRoute: () => DriverRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/signin': typeof SigninRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/reply/$token': typeof ReplyTokenRoute
  '/quote/': typeof QuoteIndexRoute
  '/garage/add': typeof DriverGarageAddRoute
  '/garage/ask': typeof DriverGarageAskRoute
  '/garage/my-car': typeof DriverGarageMyCarRoute
  '/garage/notifications': typeof DriverGarageNotificationsRoute
  '/garage/profile': typeof DriverGarageProfileRoute
  '/garage/service': typeof DriverGarageServiceRoute
  '/provider/onboarding': typeof DriverProviderOnboardingRoute
  '/provider/profile': typeof DriverProviderProfileRoute
  '/provider/requests': typeof DriverProviderRequestsRoute
  '/provider/settings': typeof DriverProviderSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/garage/': typeof DriverGarageIndexRoute
  '/provider/': typeof DriverProviderIndexRoute
  '/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
  '/garage/build/$buildId': typeof DriverGarageBuildBuildIdRoute
  '/garage/request/$id': typeof DriverGarageRequestIdRoute
  '/garage/vehicle/$id': typeof DriverGarageVehicleIdRoute
  '/provider/project/$id': typeof DriverProviderProjectIdRoute
  '/admin/providers/': typeof AuthenticatedAdminProvidersIndexRoute
  '/admin/requests/': typeof AuthenticatedAdminRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/signin': typeof SigninRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/reply/$token': typeof ReplyTokenRoute
  '/quote': typeof QuoteIndexRoute
  '/garage/add': typeof DriverGarageAddRoute
  '/garage/ask': typeof DriverGarageAskRoute
  '/garage/my-car': typeof DriverGarageMyCarRoute
  '/garage/notifications': typeof DriverGarageNotificationsRoute
  '/garage/profile': typeof DriverGarageProfileRoute
  '/garage/service': typeof DriverGarageServiceRoute
  '/provider/onboarding': typeof DriverProviderOnboardingRoute
  '/provider/profile': typeof DriverProviderProfileRoute
  '/provider/requests': typeof DriverProviderRequestsRoute
  '/provider/settings': typeof DriverProviderSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/garage': typeof DriverGarageIndexRoute
  '/provider': typeof DriverProviderIndexRoute
  '/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
  '/garage/build/$buildId': typeof DriverGarageBuildBuildIdRoute
  '/garage/request/$id': typeof DriverGarageRequestIdRoute
  '/garage/vehicle/$id': typeof DriverGarageVehicleIdRoute
  '/provider/project/$id': typeof DriverProviderProjectIdRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersIndexRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_driver': typeof DriverRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/signin': typeof SigninRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/reply/$token': typeof ReplyTokenRoute
  '/quote/': typeof QuoteIndexRoute
  '/_driver/garage/add': typeof DriverGarageAddRoute
  '/_driver/garage/ask': typeof DriverGarageAskRoute
  '/_driver/garage/my-car': typeof DriverGarageMyCarRoute
  '/_driver/garage/notifications': typeof DriverGarageNotificationsRoute
  '/_driver/garage/profile': typeof DriverGarageProfileRoute
  '/_driver/garage/service': typeof DriverGarageServiceRoute
  '/_driver/provider/onboarding': typeof DriverProviderOnboardingRoute
  '/_driver/provider/profile': typeof DriverProviderProfileRoute
  '/_driver/provider/requests': typeof DriverProviderRequestsRoute
  '/_driver/provider/settings': typeof DriverProviderSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_driver/garage/': typeof DriverGarageIndexRoute
  '/_driver/provider/': typeof DriverProviderIndexRoute
  '/_authenticated/admin/requests/$id': typeof AuthenticatedAdminRequestsIdRoute
  '/_driver/garage/build/$buildId': typeof DriverGarageBuildBuildIdRoute
  '/_driver/garage/request/$id': typeof DriverGarageRequestIdRoute
  '/_driver/garage/vehicle/$id': typeof DriverGarageVehicleIdRoute
  '/_driver/provider/project/$id': typeof DriverProviderProjectIdRoute
  '/_authenticated/admin/providers/': typeof AuthenticatedAdminProvidersIndexRoute
  '/_authenticated/admin/requests/': typeof AuthenticatedAdminRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/card'
    | '/signin'
    | '/admin/login'
    | '/admin/reset-password'
    | '/providers/$id'
    | '/quote/$token'
    | '/reply/$token'
    | '/quote/'
    | '/garage/add'
    | '/garage/ask'
    | '/garage/my-car'
    | '/garage/notifications'
    | '/garage/profile'
    | '/garage/service'
    | '/provider/onboarding'
    | '/provider/profile'
    | '/provider/requests'
    | '/provider/settings'
    | '/admin/'
    | '/garage/'
    | '/provider/'
    | '/admin/requests/$id'
    | '/garage/build/$buildId'
    | '/garage/request/$id'
    | '/garage/vehicle/$id'
    | '/provider/project/$id'
    | '/admin/providers/'
    | '/admin/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/card'
    | '/signin'
    | '/admin/login'
    | '/admin/reset-password'
    | '/providers/$id'
    | '/quote/$token'
    | '/reply/$token'
    | '/quote'
    | '/garage/add'
    | '/garage/ask'
    | '/garage/my-car'
    | '/garage/notifications'
    | '/garage/profile'
    | '/garage/service'
    | '/provider/onboarding'
    | '/provider/profile'
    | '/provider/requests'
    | '/provider/settings'
    | '/admin'
    | '/garage'
    | '/provider'
    | '/admin/requests/$id'
    | '/garage/build/$buildId'
    | '/garage/request/$id'
    | '/garage/vehicle/$id'
    | '/provider/project/$id'
    | '/admin/providers'
    | '/admin/requests'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_driver'
    | '/auth'
    | '/card'
    | '/signin'
    | '/admin/login'
    | '/admin/reset-password'
    | '/providers/$id'
    | '/quote/$token'
    | '/reply/$token'
    | '/quote/'
    | '/_driver/garage/add'
    | '/_driver/garage/ask'
    | '/_driver/garage/my-car'
    | '/_driver/garage/notifications'
    | '/_driver/garage/profile'
    | '/_driver/garage/service'
    | '/_driver/provider/onboarding'
    | '/_driver/provider/profile'
    | '/_driver/provider/requests'
    | '/_driver/provider/settings'
    | '/_authenticated/admin/'
    | '/_driver/garage/'
    | '/_driver/provider/'
    | '/_authenticated/admin/requests/$id'
    | '/_driver/garage/build/$buildId'
    | '/_driver/garage/request/$id'
    | '/_driver/garage/vehicle/$id'
    | '/_driver/provider/project/$id'
    | '/_authenticated/admin/providers/'
    | '/_authenticated/admin/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DriverRouteRoute: typeof DriverRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CardRoute: typeof CardRoute
  SigninRoute: typeof SigninRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
  QuoteTokenRoute: typeof QuoteTokenRoute
  ReplyTokenRoute: typeof ReplyTokenRoute
  QuoteIndexRoute: typeof QuoteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_driver': {
      id: '/_driver'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DriverRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/': {
      id: '/quote/'
      path: '/quote'
      fullPath: '/quote/'
      preLoaderRoute: typeof QuoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$token': {
      id: '/quote/$token'
      path: '/quote/$token'
      fullPath: '/quote/$token'
      preLoaderRoute: typeof QuoteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reply/$token': {
      id: '/reply/$token'
      path: '/reply/$token'
      fullPath: '/reply/$token'
      preLoaderRoute: typeof ReplyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_driver/garage/': {
      id: '/_driver/garage/'
      path: '/garage'
      fullPath: '/garage/'
      preLoaderRoute: typeof DriverGarageIndexRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_driver/garage/add': {
      id: '/_driver/garage/add'
      path: '/garage/add'
      fullPath: '/garage/add'
      preLoaderRoute: typeof DriverGarageAddRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_driver/garage/ask': {
      id: '/_driver/garage/ask'
      path: '/garage/ask'
      fullPath: '/garage/ask'
      preLoaderRoute: typeof DriverGarageAskRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_driver/garage/my-car': {
      id: '/_driver/garage/my-car'
      path: '/garage/my-car'
      fullPath: '/garage/my-car'
      preLoaderRoute: typeof DriverGarageMyCarRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_driver/garage/notifications': {
      id: '/_driver/garage/notifications'
      path: '/garage/notifications'
      fullPath: '/garage/notifications'
      preLoaderRoute: typeof DriverGarageNotificationsRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_driver/garage/profile': {
      id: '/_driver/garage/profile'
      path: '/garage/profile'
      fullPath: '/garage/profile'
      preLoaderRoute: typeof DriverGarageProfileRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_driver/garage/service': {
      id: '/_driver/garage/service'
      path: '/garage/service'
      fullPath: '/garage/service'
      preLoaderRoute: typeof DriverGarageServiceRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_driver/provider/': {
      id: '/_driver/provider/'
      path: '/provider'
      fullPath: '/provider/'
      preLoaderRoute: typeof DriverProviderIndexRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_driver/provider/onboarding': {
      id: '/_driver/provider/onboarding'
      path: '/provider/onboarding'
      fullPath: '/provider/onboarding'
      preLoaderRoute: typeof DriverProviderOnboardingRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_driver/provider/profile': {
      id: '/_driver/provider/profile'
      path: '/provider/profile'
      fullPath: '/provider/profile'
      preLoaderRoute: typeof DriverProviderProfileRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_driver/provider/requests': {
      id: '/_driver/provider/requests'
      path: '/provider/requests'
      fullPath: '/provider/requests'
      preLoaderRoute: typeof DriverProviderRequestsRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_driver/provider/settings': {
      id: '/_driver/provider/settings'
      path: '/provider/settings'
      fullPath: '/provider/settings'
      preLoaderRoute: typeof DriverProviderSettingsRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_authenticated/admin/providers/': {
      id: '/_authenticated/admin/providers/'
      path: '/admin/providers'
      fullPath: '/admin/providers/'
      preLoaderRoute: typeof AuthenticatedAdminProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/requests/': {
      id: '/_authenticated/admin/requests/'
      path: '/admin/requests'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AuthenticatedAdminRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/requests/$id': {
      id: '/_authenticated/admin/requests/$id'
      path: '/admin/requests/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AuthenticatedAdminRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_driver/garage/build/$buildId': {
      id: '/_driver/garage/build/$buildId'
      path: '/garage/build/$buildId'
      fullPath: '/garage/build/$buildId'
      preLoaderRoute: typeof DriverGarageBuildBuildIdRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_driver/garage/request/$id': {
      id: '/_driver/garage/request/$id'
      path: '/garage/request/$id'
      fullPath: '/garage/request/$id'
      preLoaderRoute: typeof DriverGarageRequestIdRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_driver/garage/vehicle/$id': {
      id: '/_driver/garage/vehicle/$id'
      path: '/garage/vehicle/$id'
      fullPath: '/garage/vehicle/$id'
      preLoaderRoute: typeof DriverGarageVehicleIdRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/_driver/provider/project/$id': {
      id: '/_driver/provider/project/$id'
      path: '/provider/project/$id'
      fullPath: '/provider/project/$id'
      preLoaderRoute: typeof DriverProviderProjectIdRouteImport
      parentRoute: typeof DriverRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminRequestsIdRoute: typeof AuthenticatedAdminRequestsIdRoute
  AuthenticatedAdminProvidersIndexRoute: typeof AuthenticatedAdminProvidersIndexRoute
  AuthenticatedAdminRequestsIndexRoute: typeof AuthenticatedAdminRequestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminRequestsIdRoute: AuthenticatedAdminRequestsIdRoute,
  AuthenticatedAdminProvidersIndexRoute: AuthenticatedAdminProvidersIndexRoute,
  AuthenticatedAdminRequestsIndexRoute: AuthenticatedAdminRequestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DriverRouteRouteChildren {
  DriverGarageAddRoute: typeof DriverGarageAddRoute
  DriverGarageAskRoute: typeof DriverGarageAskRoute
  DriverGarageMyCarRoute: typeof DriverGarageMyCarRoute
  DriverGarageNotificationsRoute: typeof DriverGarageNotificationsRoute
  DriverGarageProfileRoute: typeof DriverGarageProfileRoute
  DriverGarageServiceRoute: typeof DriverGarageServiceRoute
  DriverProviderOnboardingRoute: typeof DriverProviderOnboardingRoute
  DriverProviderProfileRoute: typeof DriverProviderProfileRoute
  DriverProviderRequestsRoute: typeof DriverProviderRequestsRoute
  DriverProviderSettingsRoute: typeof DriverProviderSettingsRoute
  DriverGarageIndexRoute: typeof DriverGarageIndexRoute
  DriverProviderIndexRoute: typeof DriverProviderIndexRoute
  DriverGarageBuildBuildIdRoute: typeof DriverGarageBuildBuildIdRoute
  DriverGarageRequestIdRoute: typeof DriverGarageRequestIdRoute
  DriverGarageVehicleIdRoute: typeof DriverGarageVehicleIdRoute
  DriverProviderProjectIdRoute: typeof DriverProviderProjectIdRoute
}

const DriverRouteRouteChildren: DriverRouteRouteChildren = {
  DriverGarageAddRoute: DriverGarageAddRoute,
  DriverGarageAskRoute: DriverGarageAskRoute,
  DriverGarageMyCarRoute: DriverGarageMyCarRoute,
  DriverGarageNotificationsRoute: DriverGarageNotificationsRoute,
  DriverGarageProfileRoute: DriverGarageProfileRoute,
  DriverGarageServiceRoute: DriverGarageServiceRoute,
  DriverProviderOnboardingRoute: DriverProviderOnboardingRoute,
  DriverProviderProfileRoute: DriverProviderProfileRoute,
  DriverProviderRequestsRoute: DriverProviderRequestsRoute,
  DriverProviderSettingsRoute: DriverProviderSettingsRoute,
  DriverGarageIndexRoute: DriverGarageIndexRoute,
  DriverProviderIndexRoute: DriverProviderIndexRoute,
  DriverGarageBuildBuildIdRoute: DriverGarageBuildBuildIdRoute,
  DriverGarageRequestIdRoute: DriverGarageRequestIdRoute,
  DriverGarageVehicleIdRoute: DriverGarageVehicleIdRoute,
  DriverProviderProjectIdRoute: DriverProviderProjectIdRoute,
}

const DriverRouteRouteWithChildren = DriverRouteRoute._addFileChildren(
  DriverRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DriverRouteRoute: DriverRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CardRoute: CardRoute,
  SigninRoute: SigninRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  ProvidersIdRoute: ProvidersIdRoute,
  QuoteTokenRoute: QuoteTokenRoute,
  ReplyTokenRoute: ReplyTokenRoute,
  QuoteIndexRoute: QuoteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
